2019-10-17 14:22:55,788 ERROR: Exception on /creator/create [GET] [in /Library/Python/3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/haikodidzoleit/CODING/HTBAH_creator/app/creator/routes.py", line 30, in creator_create
    return render_template('creator/creator.html', title=_('Sign In'), form=form)
  File "/Library/Python/3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Library/Python/3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Library/Python/3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Library/Python/3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Python/3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/haikodidzoleit/CODING/HTBAH_creator/app/templates/creator/creator.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Library/Python/3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/Users/haikodidzoleit/CODING/HTBAH_creator/app/templates/creator/creator.html", line 17, in root
    </div>
  File "/Users/haikodidzoleit/CODING/HTBAH_creator/app/templates/base.html", line 14, in root
    <link rel="stylesheet" href="{{ url_for('static', filename='library/bootstrap/css/bootstrap.min.css')}}">
  File "/Library/Python/3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 10, in root
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  File "/Library/Python/3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block_doc
    {% block body -%}
  File "/Library/Python/3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 39, in block_html
  File "/Library/Python/3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 92, in block_body
  File "/Users/haikodidzoleit/CODING/HTBAH_creator/app/templates/base.html", line 121, in block_content
  File "/Users/haikodidzoleit/CODING/HTBAH_creator/app/templates/creator/creator.html", line 30, in block_app_content
    <div class="card-box-c foo">
  File "/Library/Python/3.7/site-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/Library/Python/3.7/site-packages/wtforms/fields/core.py", line 155, in __call__
    return self.meta.render_field(self, kwargs)
  File "/Library/Python/3.7/site-packages/wtforms/meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "/Library/Python/3.7/site-packages/wtforms/widgets/core.py", line 120, in __call__
    for subfield in field:
  File "/Library/Python/3.7/site-packages/wtforms/fields/core.py", line 432, in __iter__
    for i, (value, label, checked) in enumerate(self.iter_choices()):
  File "/Library/Python/3.7/site-packages/wtforms/fields/core.py", line 454, in iter_choices
    for value, label in self.choices:
ValueError: not enough values to unpack (expected 2, got 1)
2019-10-17 14:24:26,469 INFO: Microblog startup [in /Users/haikodidzoleit/CODING/HTBAH_creator/app/__init__.py:84]
2019-10-17 14:27:40,422 INFO: Microblog startup [in /Users/haikodidzoleit/CODING/HTBAH_creator/app/__init__.py:84]
2019-10-17 14:28:05,734 INFO: Microblog startup [in /Users/haikodidzoleit/CODING/HTBAH_creator/app/__init__.py:84]
2019-10-17 14:28:27,383 INFO: Microblog startup [in /Users/haikodidzoleit/CODING/HTBAH_creator/app/__init__.py:84]
2019-10-17 14:28:36,893 INFO: Microblog startup [in /Users/haikodidzoleit/CODING/HTBAH_creator/app/__init__.py:84]
2019-10-17 14:28:50,965 INFO: Microblog startup [in /Users/haikodidzoleit/CODING/HTBAH_creator/app/__init__.py:84]
2019-10-17 14:29:07,636 INFO: Microblog startup [in /Users/haikodidzoleit/CODING/HTBAH_creator/app/__init__.py:84]
2019-10-17 14:29:31,140 INFO: Microblog startup [in /Users/haikodidzoleit/CODING/HTBAH_creator/app/__init__.py:84]
2019-10-18 15:43:06,143 INFO: Microblog startup [in /home/orillion/CODING/HTBAH_Character_Creator/app/__init__.py:84]
2019-10-18 15:46:22,948 INFO: Microblog startup [in /home/orillion/CODING/HTBAH_Character_Creator/app/__init__.py:84]
2019-10-18 15:53:42,358 INFO: Microblog startup [in /home/orillion/CODING/HTBAH_Character_Creator/app/__init__.py:84]
2019-10-18 15:55:50,860 INFO: Microblog startup [in /home/orillion/CODING/HTBAH_Character_Creator/app/__init__.py:84]
2019-10-18 15:57:07,444 INFO: Microblog startup [in /home/orillion/CODING/HTBAH_Character_Creator/app/__init__.py:84]
2019-10-18 15:59:09,768 INFO: Microblog startup [in /home/orillion/CODING/HTBAH_Character_Creator/app/__init__.py:84]
